# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.1.0
group=com.startraveler.rootbound
java_version=21

# Common
mod_name=Rootbound
mod_author=Startraveler
mod_id=rootbound
license=Apache-2.0
credits=
description=A library mod including block transforming and random feature selection utilities.

## Minecraft Version
minecraft_version=1.21.8
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
minecraft_version_range=[1.21.8]

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.8
parchment_version=2025.07.20

# Fabric
# The version of Fabric that is used, see https://fabricmc.net/develop/
fabric_version=0.131.0+1.21.8
fabric_loader_version=0.17.2

# Forge (Unused)
forge_version=54.0.10
forge_loader_version_range=[54,)

# NeoForge
neoforge_version=21.8.31
neoforge_loader_version_range=[4,)